// <auto-generated />
using System;
using Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(TransactionContext))]
    partial class TransactionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Data.Models.Domain.Login", b =>
                {
                    b.Property<string>("User")
                        .HasMaxLength(255)
                        .HasColumnType("char");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("char");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("char");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("char");

                    b.Property<DateTime>("ValidTo")
                        .HasMaxLength(255)
                        .HasColumnType("datetime");

                    b.HasKey("User");

                    b.ToTable("Login", (string)null);
                });

            modelBuilder.Entity("Data.Models.Domain.Settings", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("char");

                    b.Property<int>("ChainId")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("char");

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("char");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("char");

                    b.HasKey("Address");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("Data.Models.Domain.Transaction", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("char");

                    b.Property<string>("HashId")
                        .HasMaxLength(255)
                        .HasColumnType("char");

                    b.Property<decimal>("Qty")
                        .HasPrecision(50, 18)
                        .HasColumnType("integer");

                    b.HasKey("Address");

                    b.HasIndex("HashId");

                    b.ToTable("Transaction", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
